import mongoose from "mongoose";

const VideoSchema = new mongoose.Schema({
  url: { type: String, required: true, index: true },
  title: { type: String },
  durationSeconds: { type: Number },
  source: { type: String }, // youtube, coursera, etc
  summary: { type: String, default: "" }, // autogenerated summary
  indexedAt: { type: Date, default: Date.now }
}, { timestamps: true });

export default mongoose.model("Video", VideoSchema);